@extends('layouts.app')

@section('content')
    <div class="content-wrapper">
        <div class="d-flex justify-content-between align-items-center mb-3">
            <div><h4 class="mb-1">@lang('gps_inventory.inventory.title')</h4><p class="text-muted mb-0">@lang('gps_inventory.inventory.subtitle')</p></div>
            <span class="badge badge-primary">@lang('gps_inventory.inventory.governed_workflow')</span>
        </div>
        @if (session('success'))<div class="alert alert-success">{{ session('success') }}</div>@endif
        @if ($errors->any())<div class="alert alert-danger"><ul class="mb-0">@foreach ($errors->all() as $error)<li>{{ $error }}</li>@endforeach</ul></div>@endif

        <div class="row">
            <div class="col-lg-4 mb-4">
                <div class="bg-white rounded p-4 shadow-sm mb-4">
                    <h5>@lang('gps_inventory.inventory.add_contractor')</h5>
                    <form method="POST" action="{{ route('contractor-inventory.contractors.store') }}">@csrf
                        <div class="form-group"><label>@lang('gps_inventory.inventory.contractor_name')</label><input name="name" class="form-control" required></div>
                        <div class="form-group"><label>@lang('gps_inventory.inventory.company_name')</label><input name="company_name" class="form-control"></div>
                        <div class="form-row"><div class="form-group col"><label>@lang('gps_inventory.inventory.phone')</label><input name="phone" class="form-control"></div><div class="form-group col"><label>@lang('gps_inventory.inventory.email')</label><input name="email" type="email" class="form-control"></div></div>
                        <div class="custom-control custom-checkbox mb-3"><input name="auto_approve_requests" value="1" type="checkbox" class="custom-control-input" id="contractor-auto"><label class="custom-control-label" for="contractor-auto">@lang('gps_inventory.inventory.contractor_auto_approve')</label></div>
                        <textarea name="notes" class="form-control mb-3" rows="2" placeholder="@lang('gps_inventory.inventory.notes')"></textarea>
                        <button class="btn btn-primary">@lang('gps_inventory.inventory.save_contractor')</button>
                    </form>
                </div>
                <div class="bg-white rounded p-4 shadow-sm mb-4">
                    <h5>@lang('gps_inventory.inventory.add_warehouse')</h5>
                    <form method="POST" action="{{ route('contractor-inventory.warehouses.store') }}">@csrf
                        <div class="form-group"><label>@lang('gps_inventory.inventory.name')</label><input name="name" class="form-control" required></div>
                        <div class="form-group"><label>@lang('gps_inventory.inventory.type')</label><select name="type" class="form-control"><option value="main">@lang('gps_inventory.inventory.main')</option><option value="contractor">@lang('gps_inventory.inventory.contractor')</option></select></div>
                        <div class="form-group"><label>@lang('gps_inventory.inventory.contractor')</label><select name="contractor_id" class="form-control"><option value="">@lang('gps_inventory.inventory.not_applicable')</option>@foreach($contractors as $contractor)<option value="{{ $contractor->id }}">{{ $contractor->name }}</option>@endforeach</select></div>
                        <div class="form-group"><label>@lang('gps_inventory.inventory.address')</label><input name="address" class="form-control"></div><button class="btn btn-primary">@lang('gps_inventory.inventory.save_warehouse')</button>
                    </form>
                </div>
                <div class="bg-white rounded p-4 shadow-sm">
                    <h5>@lang('gps_inventory.inventory.approval_settings')</h5>
                    <form method="POST" action="{{ route('contractor-inventory.settings.update') }}">@csrf @method('PUT')
                        <div class="custom-control custom-checkbox mb-3"><input name="auto_approve_requests" value="1" type="checkbox" class="custom-control-input" id="global-auto" @checked($settings->auto_approve_requests)><label class="custom-control-label" for="global-auto">@lang('gps_inventory.inventory.enable_auto_approve')</label></div>
                        <label>@lang('gps_inventory.inventory.auto_approve_max')</label><input name="auto_approve_max_quantity" type="number" min="1" class="form-control mb-3" value="{{ $settings->auto_approve_max_quantity }}" placeholder="@lang('gps_inventory.inventory.unlimited')"><button class="btn btn-outline-primary">@lang('gps_inventory.inventory.save_settings')</button>
                    </form>
                </div>
            </div>
            <div class="col-lg-8">
                <div class="bg-white rounded p-4 shadow-sm mb-4">
                    <h5>@lang('gps_inventory.inventory.contractor_file')</h5>
                    <div class="table-responsive"><table class="table table-sm"><thead><tr><th>@lang('gps_inventory.inventory.contractor')</th><th>@lang('gps_inventory.inventory.projects_responsibilities')</th><th>@lang('gps_inventory.inventory.material_allowances')</th><th>@lang('gps_inventory.inventory.consumption_total')</th></tr></thead><tbody>
                    @forelse($contractors as $contractor)<tr><td><strong>{{ $contractor->name }}</strong><br><small>{{ $contractor->company_name }} {{ $contractor->phone ? '· '.$contractor->phone : '' }}</small></td><td>@forelse($contractor->assignments as $assignment)<div>{{ $assignment->project->project_name }} <small class="text-muted">{{ $assignment->responsibility }}</small></div>@empty<small class="text-muted">@lang('gps_inventory.inventory.none')</small>@endforelse</td><td>@forelse($contractor->allowances as $allowance)<div>{{ $allowance->product->name }}: {{ $allowance->issued_quantity }}/{{ $allowance->allowed_quantity }} {{ $allowance->project?->project_name ? '('.$allowance->project->project_name.')' : '' }}</div>@empty<small class="text-muted">@lang('gps_inventory.inventory.none')</small>@endforelse</td><td><strong>{{ $consumptionByContractor[$contractor->id] ?? 0 }}</strong></td></tr>@empty<tr><td colspan="4" class="text-center text-muted">@lang('gps_inventory.inventory.no_contractors')</td></tr>@endforelse
                    </tbody></table></div>
                </div>
                <div class="bg-white rounded p-4 shadow-sm mb-4"><h5>@lang('gps_inventory.inventory.current_stock')</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>@lang('gps_inventory.inventory.warehouse')</th><th>@lang('gps_inventory.inventory.contractor')</th><th>@lang('gps_inventory.inventory.product')</th><th>@lang('gps_inventory.inventory.sku')</th><th>@lang('gps_inventory.inventory.quantity')</th></tr></thead><tbody>@foreach($warehouses as $warehouse)@forelse($warehouse->stocks as $stock)<tr><td>{{ $warehouse->name }}</td><td>{{ $warehouse->contractor?->name ?? '—' }}</td><td>{{ $stock->product->name }}</td><td>{{ $stock->product->sku }}</td><td><strong>{{ $stock->quantity }}</strong></td></tr>@empty<tr><td>{{ $warehouse->name }}</td><td>{{ $warehouse->contractor?->name ?? '—' }}</td><td colspan="3" class="text-muted">@lang('gps_inventory.inventory.no_stock')</td></tr>@endforelse@endforeach</tbody></table></div></div>
                <div class="row">
                    <div class="col-md-6 mb-4"><div class="bg-white rounded p-4 shadow-sm h-100"><h5>@lang('gps_inventory.inventory.assign_project')</h5><form method="POST" action="{{ route('contractor-inventory.assignments.store') }}">@csrf
                        <select name="contractor_id" class="form-control mb-2" required><option value="">@lang('gps_inventory.inventory.choose_contractor')</option>@foreach($contractors as $contractor)<option value="{{ $contractor->id }}">{{ $contractor->name }}</option>@endforeach</select><select name="project_id" class="form-control mb-2" required><option value="">@lang('gps_inventory.inventory.choose_project')</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><input name="responsibility" class="form-control mb-2" placeholder="@lang('gps_inventory.inventory.responsibility')"><button class="btn btn-outline-primary">@lang('gps_inventory.inventory.save_assignment')</button></form></div></div>
                    <div class="col-md-6 mb-4"><div class="bg-white rounded p-4 shadow-sm h-100"><h5>@lang('gps_inventory.inventory.add_allowance')</h5><form method="POST" action="{{ route('contractor-inventory.allowances.store') }}">@csrf
                        <select name="contractor_id" class="form-control mb-2" required><option value="">@lang('gps_inventory.inventory.choose_contractor')</option>@foreach($contractors as $contractor)<option value="{{ $contractor->id }}">{{ $contractor->name }}</option>@endforeach</select><select name="project_id" class="form-control mb-2"><option value="">@lang('gps_inventory.inventory.all_projects')</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select><select name="product_id" class="form-control mb-2" required><option value="">@lang('gps_inventory.inventory.product')</option>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select><input name="allowed_quantity" type="number" min="1" class="form-control mb-2" placeholder="@lang('gps_inventory.inventory.allowed_quantity')" required><div class="custom-control custom-checkbox mb-2"><input name="auto_approve" value="1" type="checkbox" class="custom-control-input" id="allow-auto"><label class="custom-control-label" for="allow-auto">@lang('gps_inventory.inventory.auto_approve')</label></div><button class="btn btn-outline-primary">@lang('gps_inventory.inventory.save_allowance')</button></form></div></div>
                </div>
                <div class="bg-white rounded p-4 shadow-sm mb-4">
                    <h5>@lang('gps_inventory.inventory.new_request')</h5><form method="POST" action="{{ route('contractor-inventory.requests.store') }}">@csrf
                    <div class="form-row"><div class="form-group col-md-3"><label>@lang('gps_inventory.inventory.contractor')</label><select name="contractor_id" class="form-control" required><option value=""></option>@foreach($contractors as $contractor)<option value="{{ $contractor->id }}">{{ $contractor->name }}</option>@endforeach</select></div><div class="form-group col-md-3"><label>@lang('gps_inventory.inventory.project')</label><select name="project_id" class="form-control"><option value="">@lang('gps_inventory.inventory.all_projects')</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select></div><div class="form-group col-md-3"><label>@lang('gps_inventory.inventory.from_warehouse')</label><select name="from_warehouse_id" class="form-control" required>@foreach($mainWarehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></div><div class="form-group col-md-3"><label>@lang('gps_inventory.inventory.to_warehouse')</label><select name="to_warehouse_id" class="form-control" required>@foreach($contractorWarehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }} — {{ $warehouse->contractor?->name }}</option>@endforeach</select></div></div>
                    <div class="form-row"><div class="form-group col-md-6"><label>@lang('gps_inventory.inventory.product')</label><select name="product_id" class="form-control" required>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}{{ $product->sku ? ' ('.$product->sku.')' : '' }}</option>@endforeach</select></div><div class="form-group col-md-2"><label>@lang('gps_inventory.inventory.quantity')</label><input name="requested_quantity" type="number" min="1" class="form-control" required></div><div class="form-group col-md-4"><label>@lang('gps_inventory.inventory.notes')</label><input name="request_notes" class="form-control"></div></div><button class="btn btn-success">@lang('gps_inventory.inventory.submit_request')</button></form>
                </div>
                <div class="bg-white rounded p-4 shadow-sm mb-4"><h5>@lang('gps_inventory.inventory.requests')</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>#</th><th>@lang('gps_inventory.inventory.contractor')</th><th>@lang('gps_inventory.inventory.product')</th><th>@lang('gps_inventory.inventory.quantity')</th><th>@lang('gps_inventory.inventory.status')</th><th>@lang('gps_inventory.inventory.actions')</th></tr></thead><tbody>
                    @forelse($requests as $stockRequest)<tr><td>{{ $stockRequest->id }}</td><td>{{ $stockRequest->contractor->name }}<br><small>{{ $stockRequest->project?->project_name }}</small></td><td>{{ $stockRequest->product->name }}</td><td>{{ $stockRequest->approved_quantity ?? $stockRequest->requested_quantity }}</td><td><span class="badge badge-{{ $stockRequest->status === 'pending' ? 'warning' : ($stockRequest->status === 'issued' ? 'success' : 'secondary') }}">@lang('gps_inventory.inventory.status_'.$stockRequest->status)</span></td><td>@if($stockRequest->status === 'pending')<form class="d-inline" method="POST" action="{{ route('contractor-inventory.requests.decision', $stockRequest) }}">@csrf<input type="hidden" name="decision" value="approved"><button class="btn btn-xs btn-success">@lang('gps_inventory.inventory.approve')</button></form><form class="d-inline" method="POST" action="{{ route('contractor-inventory.requests.decision', $stockRequest) }}">@csrf<input type="hidden" name="decision" value="rejected"><button class="btn btn-xs btn-danger">@lang('gps_inventory.inventory.reject')</button></form>@elseif($stockRequest->status === 'approved')<form class="d-inline" method="POST" action="{{ route('contractor-inventory.requests.issue', $stockRequest) }}">@csrf<button class="btn btn-xs btn-primary">@lang('gps_inventory.inventory.issue')</button></form>@endif</td></tr>@empty<tr><td colspan="6" class="text-muted text-center">@lang('gps_inventory.inventory.no_requests')</td></tr>@endforelse
                </tbody></table></div></div>
                <div class="bg-white rounded p-4 shadow-sm mb-4"><h5>@lang('gps_inventory.inventory.record_consumption_return')</h5><form method="POST" action="{{ route('contractor-inventory.movements.store') }}">@csrf
                    <div class="form-row"><div class="form-group col-md-3"><select name="contractor_id" class="form-control" required><option value="">@lang('gps_inventory.inventory.contractor')</option>@foreach($contractors as $contractor)<option value="{{ $contractor->id }}">{{ $contractor->name }}</option>@endforeach</select></div><div class="form-group col-md-3"><select name="warehouse_id" class="form-control" required><option value="">@lang('gps_inventory.inventory.to_warehouse')</option>@foreach($contractorWarehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></div><div class="form-group col-md-2"><select name="project_id" class="form-control"><option value="">@lang('gps_inventory.inventory.project')</option>@foreach($projects as $project)<option value="{{ $project->id }}">{{ $project->project_name }}</option>@endforeach</select></div><div class="form-group col-md-2"><select name="product_id" class="form-control" required>@foreach($products as $product)<option value="{{ $product->id }}">{{ $product->name }}</option>@endforeach</select></div><div class="form-group col-md-2"><input name="quantity" type="number" min="1" class="form-control" placeholder="@lang('gps_inventory.inventory.quantity')" required></div></div>
                    <div class="form-row"><div class="form-group col-md-3"><select name="movement_type" class="form-control"><option value="consumption">@lang('gps_inventory.inventory.consumption')</option><option value="return">@lang('gps_inventory.inventory.return')</option></select></div><div class="form-group col-md-3"><select name="main_warehouse_id" class="form-control"><option value="">@lang('gps_inventory.inventory.return_destination')</option>@foreach($mainWarehouses as $warehouse)<option value="{{ $warehouse->id }}">{{ $warehouse->name }}</option>@endforeach</select></div><div class="form-group col-md-3"><input name="movement_date" type="date" value="{{ now()->toDateString() }}" class="form-control" required></div><div class="form-group col-md-3"><input name="reference" class="form-control" placeholder="@lang('gps_inventory.inventory.reference')"></div></div><button class="btn btn-warning">@lang('gps_inventory.inventory.save_movement')</button></form></div>
                <div class="bg-white rounded p-4 shadow-sm"><h5>@lang('gps_inventory.inventory.consumption_ledger')</h5><div class="table-responsive"><table class="table table-sm"><thead><tr><th>@lang('gps_inventory.inventory.date')</th><th>@lang('gps_inventory.inventory.contractor')</th><th>@lang('gps_inventory.inventory.project')</th><th>@lang('gps_inventory.inventory.product')</th><th>@lang('gps_inventory.inventory.movement')</th><th>@lang('gps_inventory.inventory.quantity')</th></tr></thead><tbody>@forelse($movements as $movement)<tr><td>{{ $movement->movement_date->format('Y-m-d') }}</td><td>{{ $movement->contractor?->name }}</td><td>{{ $movement->project?->project_name }}</td><td>{{ $movement->product->name }}</td><td>@lang('gps_inventory.inventory.'.$movement->movement_type)</td><td>{{ $movement->quantity }}</td></tr>@empty<tr><td colspan="6" class="text-center text-muted">@lang('gps_inventory.inventory.no_movements')</td></tr>@endforelse</tbody></table></div></div>
            </div>
        </div>
    </div>
@endsection
